app:
    image: million12/nginx-php:php70
    container_name: notyes-nginx-php7
    restart: always
    environment:
        - VIRTUAL_HOST=www.domain.com,domain.com,*.domain.com
        - LETSENCRYPT_HOST=www.domain.com,domain.com
        - LETSENCRYPT_EMAIL=me@acodify.com
    volumes:
        - ./public_html/:/data/www/default
        - ./config/hosts.d/:/etc/nginx/hosts.d/
        - ./config/11-nginx-dirs.sh:/config/init/11-nginx-dirs.sh
    links:
        - db:mysql
db:
    image: mariadb:10
    container_name: mariadb-mysql
    restart: always
    environment:
        - MYSQL_ROOT_PASSWORD=password
        - MYSQL_DATABASE=notyes
        - MYSQL_USER=notyes
        - MYSQL_PASSWORD=RFVujm123@
    volumes:
      - ./config/data:/var/lib/mysql

